[package]
authors = ["Ivan Dubrov <dubrov.ivan@gmail.com>"]
categories = ["embedded", "no-std"]
description = "Stepper motor speed ramp generator"
repository = "https://github.com/idubrov/stepgen"
name = "stepgen"
version = "0.1.3"
license = "MIT/Apache-2.0"
readme = "README.md"
exclude = [
    "docs/*"
]
edition = "2021"

[dependencies]
fixed = "1.23.0"
fixed-sqrt = "0.2.5"
fixed-macro = "1.2.0"
fugit = "0.3.6"

[package.metadata.release]
pre-release-hook = "./update-readme.sh"

[profile.release]
opt-level = 3
lto = true

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
